export const doctors = [
  {
    id: "d1",
    name: "Dr. Rajesh Sharma",
    specialization: "Cardiologist",
    department: "Cardiology",
    experience: 9,
    rating: 4.0,
    avatar: "RS",
    available: true,
    phone: "+91 9000000001",
    email: "rajesh@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d2",
    name: "Dr. Priya Mehta",
    specialization: "Cardiologist",
    department: "Cardiology",
    experience: 15,
    rating: 4.6,
    avatar: "PM",
    available: true,
    phone: "+91 9000000002",
    email: "priya@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d3",
    name: "Dr. Sunil Deshmukh",
    specialization: "Cardiologist",
    department: "Cardiology",
    experience: 7,
    rating: 4.8,
    avatar: "SD",
    available: true,
    phone: "+91 9000000003",
    email: "sunil@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d4",
    name: "Dr. Anil Patil",
    specialization: "Neurologist",
    department: "Neurology",
    experience: 17,
    rating: 4.8,
    avatar: "AP",
    available: true,
    phone: "+91 9000000004",
    email: "anil@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d5",
    name: "Dr. Asha Joshi",
    specialization: "Neurologist",
    department: "Neurology",
    experience: 17,
    rating: 4.9,
    avatar: "AJ",
    available: true,
    phone: "+91 9000000005",
    email: "asha@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d6",
    name: "Dr. Vikram Singh",
    specialization: "Neurologist",
    department: "Neurology",
    experience: 11,
    rating: 4.7,
    avatar: "VS",
    available: true,
    phone: "+91 9000000006",
    email: "vikram@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d7",
    name: "Dr. Mahesh Jadhav",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experience: 10,
    rating: 4.4,
    avatar: "MJ",
    available: true,
    phone: "+91 9000000007",
    email: "mahesh@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d8",
    name: "Dr. Nilesh More",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experience: 12,
    rating: 4.9,
    avatar: "NM",
    available: true,
    phone: "+91 9000000008",
    email: "nilesh@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d9",
    name: "Dr. Sujata Gite",
    specialization: "Orthopedic Surgeon",
    department: "Orthopedics",
    experience: 3,
    rating: 4.3,
    avatar: "SG",
    available: true,
    phone: "+91 9000000009",
    email: "sujata@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d10",
    name: "Dr. Balasaheb Pawar",
    specialization: "General Physician",
    department: "General Medicine",
    experience: 7,
    rating: 4.5,
    avatar: "BP",
    available: true,
    phone: "+91 9000000010",
    email: "balasaheb@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d11",
    name: "Dr. Shubhangi Kulkarni",
    specialization: "General Physician",
    department: "General Medicine",
    experience: 9,
    rating: 4.5,
    avatar: "SK",
    available: true,
    phone: "+91 9000000011",
    email: "shubhangi@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d12",
    name: "Dr. Ramesh Khalkar",
    specialization: "General Physician",
    department: "General Medicine",
    experience: 15,
    rating: 4.6,
    avatar: "RK",
    available: true,
    phone: "+91 9000000012",
    email: "ramesh@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d13",
    name: "Dr. Shilpa Deshpande",
    specialization: "Pediatrician",
    department: "Pediatrics",
    experience: 16,
    rating: 4.6,
    avatar: "SD",
    available: true,
    phone: "+91 9000000013",
    email: "shilpa@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d14",
    name: "Dr. Ajit Ghorpade",
    specialization: "Pediatrician",
    department: "Pediatrics",
    experience: 4,
    rating: 4.6,
    avatar: "AG",
    available: true,
    phone: "+91 9000000014",
    email: "ajit@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d15",
    name: "Dr. Neha Choudhary",
    specialization: "Pediatrician",
    department: "Pediatrics",
    experience: 9,
    rating: 4.7,
    avatar: "NC",
    available: true,
    phone: "+91 9000000015",
    email: "neha@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d16",
    name: "Dr. Kirti Shinde",
    specialization: "Gynecologist",
    department: "Gynecology",
    experience: 21,
    rating: 4.3,
    avatar: "KS",
    available: true,
    phone: "+91 9000000016",
    email: "kirti@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d17",
    name: "Dr. Mrunalini Dambal",
    specialization: "Gynecologist",
    department: "Gynecology",
    experience: 7,
    rating: 4.4,
    avatar: "MD",
    available: true,
    phone: "+91 9000000017",
    email: "mrunalini@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d18",
    name: "Dr. Pooja Malhotra",
    specialization: "Gynecologist",
    department: "Gynecology",
    experience: 16,
    rating: 4.6,
    avatar: "PM",
    available: true,
    phone: "+91 9000000018",
    email: "pooja@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d19",
    name: "Dr. Pravin Sangle",
    specialization: "Dermatologist",
    department: "Dermatology",
    experience: 4,
    rating: 4.9,
    avatar: "PS",
    available: true,
    phone: "+91 9000000019",
    email: "pravin@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
  {
    id: "d20",
    name: "Dr. Ayesha Shaikh",
    specialization: "Dermatologist",
    department: "Dermatology",
    experience: 6,
    rating: 4.6,
    avatar: "AS",
    available: true,
    phone: "+91 9000000020",
    email: "ayesha@hms.com",
    workingHours: "Mon-Fri 9AM-5PM",
  },
];
